import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { Report } from "@/types/api";

const styles = StyleSheet.create({
  page: { flexDirection: 'column', padding: 40, fontFamily: 'Helvetica' },
  header: { marginBottom: 20, borderBottom: '1 solid #ccc', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold' },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
  metaText: { fontSize: 10, color: '#666' },
  section: { marginTop: 20 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 10, color: '#0F766E' },
  flagCard: { padding: 10, backgroundColor: '#f9f9f9', borderRadius: 4, marginBottom: 10, borderLeft: '3 solid #d97706' },
  criticalCard: { borderLeft: '3 solid #dc2626' },
  testName: { fontSize: 12, fontWeight: 'bold' },
  testVal: { fontSize: 11, marginTop: 4 },
  questionsTitle: { fontSize: 10, fontWeight: 'bold', marginTop: 8, color: '#333' },
  questionItem: { fontSize: 9, marginTop: 4, paddingLeft: 10 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#999', fontSize: 8, borderTop: '1 solid #eee', paddingTop: 10 }
});

export const DoctorSummaryPDF = ({ report }: { report: Report }) => {
  const flags = report.values.filter(v => ['high', 'low', 'critical'].includes(v.flag || ""));

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Clinical Summary</Text>
          <View style={styles.metaRow}>
            <Text style={styles.metaText}>Patient: {report.patientName || 'Not Specified'}</Text>
            <Text style={styles.metaText}>Date: {new Date(report.reportDate).toLocaleDateString()}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaText}>Lab: {report.labName}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Flagged Values requiring attention</Text>
          {flags.map((val) => (
            <View key={val.id} style={[styles.flagCard, val.flag === 'critical' ? styles.criticalCard : {}]}>
              <Text style={styles.testName}>{val.name} ({val.category})</Text>
              <Text style={styles.testVal}>{val.value} {val.unit} (Ref: {val.referenceRangeLow} - {val.referenceRangeHigh})</Text>
              
              {val.questionsForDoctor && val.questionsForDoctor.length > 0 && (
                 <>
                   <Text style={styles.questionsTitle}>Questions to discuss:</Text>
                   {val.questionsForDoctor.map((q, i) => (
                     <Text key={i} style={styles.questionItem}>• {q}</Text>
                   ))}
                 </>
              )}
            </View>
          ))}
          {flags.length === 0 && <Text style={{fontSize: 10}}>No abnormal values flagged by the system.</Text>}
        </View>
        
        <Text style={styles.footer}>Generated by Nidan — an AI tool for preliminary lab report translation. Not a diagnostic tool. Discuss all findings with a physician.</Text>
      </Page>
    </Document>
  );
};
